### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by AmiDavidW** [Akshay-Thakare/cf-kafka-proxy#1]
Hi @Akshay-Thakare,

Thanks for building this proxy.

I'm trying it and got this error when using docker compose:

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='kafka-service-...', port=443): Max retries exceeded with url: /v1/.../token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9d4f9ad700>: Failed to establish a new connection: [Errno -2] Name does not resolve'))

What could be the possible cause?

Best  Regards,
David

**Comment by Akshay-Thakare** [comment]
Resolved over email, passcode field was not set.
